spring.application.name=journalApp

spring.mongodb.uri=mongodb+srv://yanil:buddhaa@cluster0.jvekn6j.mongodb.net/?appName=Cluster0
spring.mongodb.database=journalDB
spring.data.mongodb.auto-index-creation=true

