spring.application.name=journalApp

spring.mongodb.uri=mongodb+srv://yanil02:Buddha%402468@cluster0.4fiydeq.mongodb.net/?appName=Cluster0
spring.mongodb.database=journalDB
spring.data.mongodb.auto-index-creation=true